language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
os:
  - linux
# command to install dependencies
install: 
  - pip install git+https://github.com/autonlab/DeepSurvivalMachines.git
  - pip install --upgrade pytest 
  - pip install --upgrade pylint

# command to run tests
script:
  - python -m pytest tests/
  - pylint --fail-under=8 dsm/
